"""
Unit tests for script_generator.py — _claim_id and generate_script.
"""
from __future__ import annotations

import hashlib
import os
import sys
from typing import Any, Dict, List, Optional
from unittest.mock import MagicMock, patch

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from script_generator import _claim_id, generate_script


# ---------------------------------------------------------------------------
# _claim_id
# ---------------------------------------------------------------------------


def test_claim_id_is_deterministic():
    id1 = _claim_id("job-1", 0, 0)
    id2 = _claim_id("job-1", 0, 0)
    assert id1 == id2


def test_claim_id_different_slide_different_id():
    assert _claim_id("job-1", 0, 0) != _claim_id("job-1", 1, 0)


def test_claim_id_different_segment_different_id():
    assert _claim_id("job-1", 0, 0) != _claim_id("job-1", 0, 1)


def test_claim_id_is_sha256():
    cid = _claim_id("job-x", 2, 3)
    expected = hashlib.sha256("job-x|2|3".encode("utf-8")).hexdigest()
    assert cid == expected


# ---------------------------------------------------------------------------
# generate_script — minimal shape
# ---------------------------------------------------------------------------


def _make_llm(text="Slide text generated by LLM."):
    provider = MagicMock()
    provider.generate_segment.return_value = text
    return provider


def test_generate_script_empty_plan():
    llm = _make_llm()
    result = generate_script(
        job_id="job-1",
        explain_plan={"sections": []},
        unified_graphs_by_slide={},
        evidence_index={"evidence_items": []},
        entity_to_evidence={},
        llm_provider=llm,
    )
    assert result["schema_version"] == "1.0"
    assert result["job_id"] == "job-1"
    assert result["draft"] is True
    assert result["segments"] == []


def test_generate_script_one_section():
    llm = _make_llm("This slide introduces the architecture.")
    explain_plan = {
        "sections": [
            {"slide_index": 0, "entity_ids": ["ent1"], "evidence_ids": ["ev1"], "section_type": "body"},
        ]
    }
    result = generate_script(
        job_id="job-2",
        explain_plan=explain_plan,
        unified_graphs_by_slide={},
        evidence_index={"evidence_items": [{"evidence_id": "ev1", "slide_index": 0}]},
        entity_to_evidence={"ent1": ["ev1"]},
        llm_provider=llm,
    )
    assert len(result["segments"]) == 1
    seg = result["segments"][0]
    assert seg["text"] == "This slide introduces the architecture."
    assert seg["slide_index"] == 0
    assert "claim_id" in seg


def test_generate_script_segment_claim_ids_are_unique():
    llm = _make_llm()
    sections = [
        {"slide_index": i, "entity_ids": [], "evidence_ids": [], "section_type": "body"}
        for i in range(5)
    ]
    result = generate_script(
        job_id="job-3",
        explain_plan={"sections": sections},
        unified_graphs_by_slide={},
        evidence_index={"evidence_items": []},
        entity_to_evidence={},
        llm_provider=llm,
    )
    claim_ids = [s["claim_id"] for s in result["segments"]]
    assert len(claim_ids) == len(set(claim_ids))


def test_generate_script_evidence_ids_grounded_from_index():
    """When entity_ids and evidence_ids are empty, evidence from slide is pulled in."""
    llm = _make_llm()
    sections = [{"slide_index": 0, "entity_ids": [], "evidence_ids": [], "section_type": "body"}]
    evidence_index = {
        "evidence_items": [
            {"evidence_id": "ev-fallback", "slide_index": 0, "kind": "TEXT_SPAN"},
        ]
    }
    result = generate_script(
        job_id="job-4",
        explain_plan={"sections": sections},
        unified_graphs_by_slide={},
        evidence_index=evidence_index,
        entity_to_evidence={},
        llm_provider=llm,
    )
    seg = result["segments"][0]
    # Grounding: at least one evidence item added from slide
    assert "ev-fallback" in seg["evidence_ids"]


def test_generate_script_entity_to_evidence_merged():
    """Entity-linked evidence should be merged into segment evidence_ids."""
    llm = _make_llm()
    sections = [{"slide_index": 0, "entity_ids": ["ent-a"], "evidence_ids": [], "section_type": "body"}]
    result = generate_script(
        job_id="job-5",
        explain_plan={"sections": sections},
        unified_graphs_by_slide={},
        evidence_index={"evidence_items": []},
        entity_to_evidence={"ent-a": ["ev-linked-1", "ev-linked-2"]},
        llm_provider=llm,
    )
    seg = result["segments"][0]
    assert "ev-linked-1" in seg["evidence_ids"]
    assert "ev-linked-2" in seg["evidence_ids"]


def test_generate_script_llm_called_once_per_section():
    llm = _make_llm()
    sections = [
        {"slide_index": i, "entity_ids": [], "evidence_ids": [], "section_type": "body"}
        for i in range(4)
    ]
    generate_script(
        job_id="job-6",
        explain_plan={"sections": sections},
        unified_graphs_by_slide={},
        evidence_index={"evidence_items": []},
        entity_to_evidence={},
        llm_provider=llm,
    )
    assert llm.generate_segment.call_count == 4


def test_generate_script_used_hedging_false_by_default():
    llm = _make_llm()
    sections = [{"slide_index": 0, "entity_ids": [], "evidence_ids": [], "section_type": "body"}]
    result = generate_script(
        job_id="job-7",
        explain_plan={"sections": sections},
        unified_graphs_by_slide={},
        evidence_index={"evidence_items": []},
        entity_to_evidence={},
        llm_provider=llm,
    )
    assert result["segments"][0]["used_hedging"] is False


def test_generate_script_passes_graph_to_llm():
    llm = _make_llm()
    graph = {"nodes": [{"node_id": "n1"}], "edges": [], "clusters": []}
    sections = [{"slide_index": 0, "entity_ids": ["n1"], "evidence_ids": [], "section_type": "body"}]
    generate_script(
        job_id="job-8",
        explain_plan={"sections": sections},
        unified_graphs_by_slide={0: graph},
        evidence_index={"evidence_items": []},
        entity_to_evidence={},
        llm_provider=llm,
    )
    call_kwargs = llm.generate_segment.call_args.kwargs
    assert call_kwargs.get("graph") == graph


def test_generate_script_has_created_at():
    llm = _make_llm()
    result = generate_script(
        job_id="job-9",
        explain_plan={"sections": []},
        unified_graphs_by_slide={},
        evidence_index={"evidence_items": []},
        entity_to_evidence={},
        llm_provider=llm,
    )
    assert "created_at" in result
    assert result["created_at"].endswith("Z")


def test_generate_script_intro_section_context_bundle_used():
    """intro section_type activates context_bundle path when provided."""
    llm = _make_llm()
    bundle = {"_policy": None, "notes": "intro notes"}
    sections = [{"slide_index": 0, "entity_ids": [], "evidence_ids": [], "section_type": "intro"}]

    with patch("script_generator.narration_policy", return_value=("notes", [], False)), \
         patch("script_generator.build_context_bundles_per_slide", return_value={0: bundle}):
        result = generate_script(
            job_id="job-10",
            explain_plan={"sections": sections},
            unified_graphs_by_slide={},
            evidence_index={"evidence_items": [{"evidence_id": "ev-notes", "slide_index": 0}]},
            entity_to_evidence={},
            llm_provider=llm,
            slides_notes_and_text=[("intro notes", "slide text")],
        )

    assert len(result["segments"]) == 1
